GET http://localhost:3000/task

####
GET http://localhost:3000/task/1

####
PATCH http://localhost:3000/task/2/completed/false

####
POST http://localhost:3000/task
Content-Type: application/json

{
    "description": "teste"
}

####
DELETE http://localhost:3000/task/1
